### ISSUE TITLE
RateLimiter blocks a whole thread

### ISSUE THREAD

**Issue by danielnaumau** [traveltime-dev/traveltime-sdk-nodejs#59]
We had to disable rateLimiter by default because it blocks a thread and it doesn't let sending concurrent requests. 

I think that it would be great to use a lib for such purposes instead of custom implementation

**Comment by MockusTravelTime** [comment]
Node.js is designed to be a single-threaded, event-driven platform, and its core architecture is based on the event loop. SDK functions that call API are all Promises so they allow you to write your own non-blocking code. Currently we don’t plan on adding support for [worker threads](https://nodejs.org/api/worker_threads.html) since we don’t do CPU intensive tasks on SDK side.
